language: cpp
dist: xenial
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - xorg-dev
      - libgl1-mesa-dev

git:
  submodules: false

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.2-xenial -y
  - sudo apt-get update -qq --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
  - sudo apt-get install -qq qt512base qt512charts-no-lgpl qt512svg
  - source /opt/qt512/bin/qt512-env.sh;
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - mkdir -p $TRAVIS_BUILD_DIR/packaging/appimage/qppcad
  - wget -c https://www.python.org/ftp/python/3.6.8/Python-3.6.8rc1.tgz
  - tar -xvzf ./Python-3.6.8rc1.tgz -C $TRAVIS_BUILD_DIR/packaging/appimage

script:
 - export CC=gcc-7 ;
 - export CXX=g++-7 ;
 - cd $TRAVIS_BUILD_DIR/packaging/appimage/Python-3.6.8rc1
 - ./configure --prefix=$TRAVIS_BUILD_DIR/packaging/appimage/qppcad > myconfigure.log 2>&1
 - make > mymake.log 2>&1
 - make install > mymakeinstall.log 2>&1
 - cd $TRAVIS_BUILD_DIR
 - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$TRAVIS_BUILD_DIR/packaging/appimage/qppcad/bin/python3 -DBUILD_QC=OFF -DPYTHON_BINDINGS=OFF -DBUILD_EXAMPLES=OFF -DQPPCAD_TESTS=OFF && cmake --build .
 - cd $TRAVIS_BUILD_DIR/packaging/appimage
 - ./make_appimage.sh
 - ls -lrt
 - ./upload.sh ./qppcad-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

env:
  global:
    - MAKEFLAGS="-j 2"
